### ISSUE TITLE
Use an environment variable in BlueaAPI to get beamline+hutch

### ISSUE THREAD

**Issue by olliesilvester** [DiamondLightSource/i19-bluesky#41]
See https://github.com/DiamondLightSource/i19-bluesky/pull/29#discussion_r2017031758

**Comment by noemifrisina** [comment]
Set the beamline via an environment variable in the blueapi helmchart, eg for vmxm:

```
blueapi:
  extraEnvVars: 
    - name: BEAMLINE
      value: i02-1
    - name: ZOCALO_CONFIG
      value: /dls_sw/apps/zocalo/live/configuration.yaml
```

so we don't have to pass it to log set up every time but can just read it.
